CertTrack/Controllers/EmployeeDatumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CertTrack.Contexts;
using CertTrack.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;

// This controller works with a database view.

namespace CertTrack.Controllers
{
    //[Authorize(Roles = "CITY\\Fertilizer Certification")]
    [Authorize]
    public class EmployeeDatumController : Controller
    {
        private readonly CertTrackContext _context;

        public EmployeeDatumController(CertTrackContext context)
        {
            _context = context;
        }

        
        public async Task<IActionResult> Index()
        {
           // var test1 = await _context.EmployeeDatum.ToListAsync();
            return View(await _context.EmployeeDatum.ToListAsync());
        }
        


        //   Use this to print out the query string to console for debugging....
         
        /*
        public List<CertTrack.Models.EmployeeData> Index()
        {
            var query = _context.EmployeeDatum;

            var queryString = query.ToQueryString();

            Console.WriteLine(queryString);

            return query.ToList();

        }
        */

        public async Task<IActionResult> Index2()
        {
            return View();
        }


        [HttpPost]
        public async  Task<IActionResult> AjaxMethod()
        {

            List<EmployeeData> employeedatum = await _context.EmployeeDatum.ToListAsync();

            var Jsontest1 = Json(JsonConvert.SerializeObject(employeedatum));

            return Json(JsonConvert.SerializeObject(employeedatum));
        }



    }


}

CertTrack/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CertTrack.Contexts;
using CertTrack.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using System.Text;
using AutoMapper;
using AutoMapper.QueryableExtensions;

namespace CertTrack.Controllers
{
    //[Authorize(Roles = "CITY\\Fertilizer Certification")]
    [Authorize]
    public class EmployeesController : Controller
    {
        private readonly CertTrackContext _context;

        private readonly IMapper _mapper;

        //public EmployeesController(IMapper mapper) => _mapper = mapper;

        public EmployeesController(CertTrackContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employees.ToListAsync());
        }

        public IActionResult Index_dt()
        {
            return View();
        }

        public async Task<IActionResult> SelectEmployee()
        {

            ViewData["EmployeeId"] = new SelectList(_context.Employees.OrderBy(Employees => Employees.LastName), "EmployeeId", "FullName");
            
            return View();
        }

        public async Task<IActionResult> EmployeeSummary(int? EmployeeId)
        {

            if (EmployeeId == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == EmployeeId);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> DetailsSummary(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmployeeId,FirstName,LastName,MiddleInitial,EmpPhone,EmpPhoneExt,EmpEmail,DateOfBirth,StreetAddress1,StreetAddress2,City,AddressState,Zip1,Zip2,EmpCompanyId,ApplicatorTeam")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return RedirectToAction("Index", "EmployeeDatum");
            }
            //return View(employee);
            return RedirectToAction("Index", "EmployeeDatum");
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                    //.Include(e => e.CompanyEmployees)
                    //.ThenInclude(e => e.Company)
                     .FindAsync(id);
                    //.FirstOrDefaultAsync(i => i.EmployeeId == id.Value);
                    //.SingleOrDefaultAsync(i => i.EmployeeId == id.Value)



            if (employee == null)
            {
                return NotFound();
            }
             return View(employee);
           // return RedirectToAction("Index", "EmployeeDatum");
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EmployeeId,FirstName,LastName,MiddleInitial,EmpPhone,EmpPhoneExt,EmpEmail,DateOfBirth,StreetAddress1,StreetAddress2,City,AddressState,Zip1,Zip2,EmpCompanyId,ApplicatorTeam")] Employee employee)
        {
            if (id != employee.EmployeeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.EmployeeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                // return RedirectToAction(nameof(Index));
                return RedirectToAction("Index", "EmployeeDatum");
            }
            // return View(employee);
            return RedirectToAction("Index", "EmployeeDatum");
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {

                if (id == null)
                {
                    return NotFound();
                }

                var employee = await _context.Employees
                        .FirstOrDefaultAsync(m => m.EmployeeId == id);

                if (employee == null)
                {
                    return NotFound();
                }

              return View(employee);
          //  return RedirectToAction("Index", "EmployeeDatum");

        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _context.Employees.FindAsync(id);
            _context.Employees.Remove(employee);

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateException e)
            {

                return Content("There are still certificate records attached to this employee, they must be deleted first.  Please hit the back button to return to the application.");

            }

            // return RedirectToAction(nameof(Index));
            return RedirectToAction("Index", "EmployeeDatum");
        }

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.EmployeeId == id);
        }

        [HttpPost]
        public IActionResult AjaxMethod()
        {

            List<Employee> employees = _context.Employees.ToList();

            return Json(JsonConvert.SerializeObject(employees));
        }

        // Below are attempts to include Company Name in the index view but they all fail.
        
        [HttpPost]
        // public IActionResult AjaxMethod()
        public async Task<String> AjaxMethod3()
        {

            //List<Employee> employees = _context.Employees
            var employees2 = await _context.Employees
                .Include(e => e.CompanyEmployees)
                .ThenInclude(e => e.Company)
                .ToListAsync();

            //return Json(JsonConvert.SerializeObject(employees));


            var test2 = JsonConvert.SerializeObject(employees2, new JsonSerializerSettings { MaxDepth = 2 });

            return JsonConvert.SerializeObject(employees2, new JsonSerializerSettings { MaxDepth = 3 });
            //return JsonConvert.SerializeObject(employees2);
        }

        /*
        public async Task<IEnumerable<EmployeeViewModel>> AjaxMethod4()
        {
            return await _context.Employees
                .Include(e => e.CompanyEmployees)
                .ThenInclude(e => e.Company)
                .Select(pa => new EmployeeViewModel()
            {
                FirstName = pa.FirstName,
                LastName = pa.LastName,
                CompanyName = pa.Company.CompanyName
            }).ToListAsync();
        }
        */

        //public async Task<IEnumerable<EmployeeViewModel>> AjaxMethod4()
        //public async Task<string> AjaxMethod4()

        /*
        public Task<string> AjaxMethod4()
        {
            /*
            return await _context.Employees
                                         .Include(i => i.CompanyEmployees)
                                         .ThenInclude(i => i.Company)
                                         ._mapper.ProjectTo<EmployeeViewModel>(_context.Set<EmployeeViewModel>())
                                         .ToListAsync();
            */

           // return _mapper.ProjectTo<EmployeeViewModel>(_context.Employees

        /*

              List < EmployeeViewModel > item = _context.Employees
                                     .Include(i => i.CompanyEmployees)
                                     .ThenInclude(i => i.Company)
                                     .ProjectTo<EmployeeViewModel>()

CertTrack/Views/EmployeeDatum/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout_dt.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
         /*   font-family: Arial;
               font-size: 10pt;  */
        }

        /* This needs adjusting to keep buttons on page and the Select number of records option disappeared  */
        
        /*
        .dataTables_wrapper {
            position: relative; 
        }


        
        div#tblEmployee_wrapper { 
        
        width: 95%;  
        float: right;             
                                  }
            */

        
        /*
        div.tblEmployee_length {
        
        z-index: 1;
        left: 5px;
        
        
        }


        div.dataTables_length {
            z-index: 1;
            left: 5px;

        }

           */

        div.floatright {
            display: inline;
            float: right;
            padding-left: 5px;
            padding-bottom: 5px;
            padding-right: 5px;
        }

        div.dt-buttons.btn-group.flex-wrap {
            display: inline;
            float: right;
            padding-left: 5px;
        }

        tfoot input {
            width: 100%;
            padding: 3px;
            box-sizing: border-box;
        }
        

    </style>
</head>
<body>

    <p>
      <!--  <a asp-action="Employees/Create">Create New</a>  -->
        <!-- Html.ActionLink("Create New", "Create", "Employees", null, new { id = "OT", style = "color: #4CACFC" }) -->
        <a asp-controller="Employees" asp-action="Create">Create New</a>
    </p>

    <div style="width: 100%">
        <table id="tblEmployee" cellpadding="0" cellspacing="0" border="1" style="border-collapse:collapse">
            <thead>
                <tr>
                    <th>Employee Id</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Middle Initial  </th>
                    <th>Phone  </th>
                    <th>PhoneExt  </th>
                    <th>Email  </th>
                    <th>DOB </th>
                    <th>Street Address 1</th>
                    <th>Street Address 2  </th>
                    <th>Comment</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Zip1</th>
                    <th>Zip2</th>
                    <th>Company</th>
                    <th>Applicator Team</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <!--<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script> -->
    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
        $(function () {
            $.ajax({
                type: "POST",
                url: "/EmployeeDatum/AjaxMethod",
                data: '{}',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: OnSuccess,
                failure: function (response) {
                    alert(response);
                },
                error: function (response) {
                    alert(response);
                }
            });
        });
        function OnSuccess(response) {
            var employees = eval(response);
            $("#tblEmployee").DataTable(
                {   
                    //dom: 'Bfrtip',
                    dom: 'lf<"floatright"B>rtip',
                    //dom: 'lrtip',
                    buttons: [

                        {
                            extend: 'copyHtml5',
                            exportOptions: {
                                columns: ':visible'
                            }
                        },
                        {
                            extend: 'excelHtml5',
                            exportOptions: {
                                columns: ':visible'
                            }
                        },
                        {
                            extend: 'csvHtml5',
                            exportOptions: {
                                columns: ':visible'
                            }
                        },
                        {
                            extend: 'pdfHtml5',
                            exportOptions: {
                                columns: ':visible'
                            }
                        },
                        'colvis',
                        {
                            extend: 'print',
                            exportOptions: {
                                columns: ':visible'
                            }
                        }
                        //'searchBuilder',
                        //'searchPanes'
                    ],   
                    bLengthChange: true,
                    lengthMenu: [[5, 10, -1], [5, 10, "All"]],
                    bFilter: true,
                    bSort: true,
                    bPaginate: true,
                    data: employees,
                    columns: [{ 'data': 'EmployeeId' },
                    { 'data': 'FirstName' },
                    { 'data': 'LastName' },
                    { 'data': 'MiddleInitial' },
                    { 'data': 'EmpPhone' },
                    { 'data': 'EmpPhoneExt' },
                    { 'data': 'EmpEmail' },
                    {
                            'data': 'DateOfBirth', render: function (data, type, row) {
                            if (data == null) { return "" }
                            else {
                                return data.substr(0, 10);
                            }
                            }
                        },
                    { 'data': 'StreetAddress1' },
                    { 'data': 'StreetAddress2' },
                    { 'data': 'EmployeeComment' },
                    { 'data': 'City' },
                    { 'data': 'AddressState' },
                    { 'data': 'Zip1' },
                    { 'data': 'Zip2' },
                    { 'data': 'CompanyName' },
                    { 'data': 'ApplicatorTeam' }],
                    columnDefs: [
                        {
                            targets: 17,
                            data: null,
                            render: function (data, type, row, meta) {

                                return '<a class="btn btn - link" role="button" href="Employees/Edit/' + data["EmployeeId"] + '" >Edit</a>';
                            }
                        },
                        {
                            targets: 18,
                            data: null,
                            render: function (data, type, row, meta) {

                                return '<a class="btn btn - link" role="button" href="Employees/Details/' + data["EmployeeId"] + '" >Details</a>';
                            }
                        },
                        {
                            targets: 19,
                            data: null,
                            render: function (data, type, row, meta) {

                                return '<a class="btn btn - link" role="button" href="Employees/Delete/' + data["EmployeeId"] + '" >Delete</a>';
                            },

                            orderable: false
                        },
                    ]
                });
        };
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.11.2/b-2.0.0/b-colvis-2.0.0/b-html5-2.0.0/b-print-2.0.0/datatables.min.css" />

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.11.2/b-2.0.0/b-colvis-2.0.0/b-html5-2.0.0/b-print-2.0.0/datatables.min.js"></script>


    <script src="~/js/site.js" asp-append-version="true"></script>

</body>
</html>

CertTrack/Views/EmployeeDatum/Indexold.cshtml
@model IEnumerable<CertTrack.Models.EmployeeData>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Expr3)
            </th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Expr3)
                </td>

            </tr>
        }
    </tbody>
</table>